version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker buildx build --platform=linux/amd64 -t web:1 .
      - docker tag web:1 489073718747.dkr.ecr.us-east-1.amazonaws.com/kacperkingsford
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 489073718747.dkr.ecr.us-east-1.amazonaws.com/kacperkingsford
